#!/bin/bash

alias mi='micro'

alias md='mkdir -pv'
alias cp='cp -rv'
alias mv='mv -v'
alias rm='rm -rv'

alias link='ln -svi'

alias cls='clear'

alias path='echo -e ${PATH//:/\\n}'
alias nowt='date +"%T"'
alias nowd='date +"%d-%m-%Y"'
alias nowdt='date +"%d-%m-%Y %T"'

alias follow='tail -fn +1'

alias create-uuid='uuidgen'

alias git-ff='git pull --ff-only'
