#!/bin/bash

alias mi='micro'

alias md='mkdir -pv'
alias cp='cp -rv'
alias mv='mv -v'
alias rm='rm -rv'

alias cm-ux='chmod -v u+x'
alias cm-ax='chmod -v a+x'
alias cm-urw='chmod -v 600'

alias link='ln -svi'

alias cls='clear'

alias path='echo -e ${PATH//:/\\n}'
alias nowt='date +"%T"'
alias nowd='date +"%d-%m-%Y"'
alias nowdt='date +"%d-%m-%Y %T"'

alias follow='tail -fn +1'

alias create-uuid='uuidgen'

alias git-ff='git pull --ff-only'
alias git-reset='git reset --hard'

alias prune-backups='find ~/backup -name "*.backup" -type f -mtime +30 -delete'
