#!/bin/bash
# shellcheck disable=1090

function dot_reset() {
  source "${HOME}/.bashrc"
}

function sd() {
  declare -A dir_list
  while IFS="=" read -r key value; do
    dir_list[$key]=$value
  done < "${HOME}/.dot_dirs"
  if [ "$#" -eq 0 ]; then
    cat "${HOME}/.dot_dirs"
  elif [ "$#" -eq 1 ]; then
    if [[ -v dir_list[$1] ]]; then
      cd "${dir_list[$1]}" || exit
    fi
  else
    if [ -z "$2" ]; then
      unset "dir_list[$1]"
    else
      dir_list[$1]=$2
    fi
    for key in "${!dir_list[@]}"; do
      echo "${key}=${dir_list[$key]}"
    done > "${HOME}/.dot_dirs"
  fi
}
