#!/bin/bash

alias ll='ls -vlAhgF --color=auto --group-directories-first'
alias lf='ls -pvlAhgF --color=auto --group-directories-first | grep -v /'
alias ld='\ls --color=auto -vhld -- */'
alias cll='clear && ls -vlAhgF --color=auto --group-directories-first'

alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ~='cd ~'

alias ldu='du -h -s *'

alias df='df -H --total'
alias ports='netstat -tulanp'

alias meminfo='free -mlt'
alias cpuinfo='lscpu'
alias hostinfo='hostnamectl'

alias install='sudo apt install'
alias sysd='sudo systemctl'
alias reload='sudo systemctl reload'
alias restart='sudo systemctl restart'
alias status='sudo systemctl status'
alias start='sudo systemctl start'
alias stop='sudo systemctl stop'
alias reboot='sudo reboot'
