#!/bin/bash
# shellcheck disable=1090

function dot-update() {
  (cd "${DOT}" && git pull --ff-only)
  dot-reset
}

function create-key() {
  cat /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | fold -w "${1:-128}" | head -n 1
}

function lsd() {
  declare -A dir_list
  while IFS="=" read -r key value; do
    dir_list[$key]=$value
  done < "${HOME}/.dot_dirs"
  if [[ -v dir_list[$1] ]]; then
    clear
    ll "${dir_list[$1]}"
  fi
}

function cdl() {
  cd "${1}" && ll "${PWD}"
}

function mkcd() {
  mkdir -p -- "$1" && cd -P -- "$1" || exit
}

function clone-all() {
  repo_list="${HOME}/code/repo-list"
  while read -r repo; do
    echo "${repo}"
  done < "${repo_list}"
}

function pull-all() {
  for repo in */.git; do
    echo "${repo}"
    (cd "${repo}/.." && git pull --ff-only)
  done
}

function set-title() {
  if [ -z "$PS1_BACK" ]; then
    PS1_BACK="$PS1"
  fi
  TITLE="\[\e]0;$*\a\]"
  PS1="${PS1_BACK}${TITLE}"
}

function git-branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/[\1] /'
}

function trim() {
  local trimmed="$1"
  trimmed=$(ltrim "${trimmed}")
  trimmed=$(rtrim "${trimmed}")
  echo "${trimmed}"
}

function ltrim() {
  local trimmed="$1"
  while [[ $trimmed == ' '* ]]; do
    trimmed="${trimmed## }"
  done
  echo "${trimmed}"
}

function rtrim() {
  local trimmed="$1"
  while [[ $trimmed == *' ' ]]; do
    trimmed="${trimmed%% }"
  done
  echo "${trimmed}"
}

function percent-used() {
  divisor=$(("$1" * "$2"))
  if [[ "$divisor" -gt 0 ]]; then
    percent=$(echo "100 / $divisor" | bc -l)
    percent=${percent%.*}
    echo "${percent:-0}"
  fi
}

function percent-remain() {
  percent=$(echo "(100 / $1) * ($1 - $2)" | bc -l)
  percent=${percent%.*}
  echo "${percent:-0}"
}
