#!/bin/bash

export PATH=${PATH}:${HOME}/bin
export PATH=${PATH}:${HOME}/.bin

export MICRO_TRUECOLOR=1

source $DOT/lib/aliases
source $DOT/lib/zsh_aliases
source $DOT/lib/functions
source $DOT/lib/zsh_fns

